apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    domain = grafana.lab.ru
    root_url = https://grafana.lab.ru/
    serve_from_sub_path = false

    [security]
    allow_embedding = true

    [dataproxy]
    logging = true
